export default [
  {
    path: '/user',
    layout: false,
    routes: [
      { path: '/user/login', component: './User/Login' },
      { path: '/user/register', component: './User/Register' },
    ],
  },
  { path: '/welcome', icon: 'home', component: './Welcome', name: '首页' },
  {
    path: '/admin/user',
    icon: 'user',
    name: '用户管理',
    access: 'canAdmin',
    component: './Admin/User',
  },
  {
    path: '/material',
    icon: 'appstore',
    name: '物资管理',
    access: 'canUser',
    component: './Material',
  },
  {
    path: '/stock',
    icon: 'database',
    name: '库存管理',
    access: 'canAdmin',
    component: './Stock',
  },
  {
    path: '/apply',
    icon: 'profile',
    name: '审批管理',
    access: 'canUser',
    component: './Apply',
  },
  {
    path: '/notice',
    icon: 'bell',
    name: '预警通知',
    access: 'canUser',
    component: './WarnNotice',
  },
  {
    path: '/admin/report',
    icon: 'barChart',
    name: '报表统计',
    access: 'canAdmin',
    component: './Report',
  },
  { path: '/admin', redirect: '/admin/user' },
  { path: '/', redirect: '/welcome' },
  { path: '*', layout: false, component: './404' },
];
